# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "400d32a75b5f88c302e71295098cfcaf"
application_url = "https://example.com"
embedded = true
name = "Moxie SEO"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_content,write_content,read_themes,write_themes,read_script_tags,write_script_tags"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
